[package]
name = "untitled"
version = "1.0.0"
authors = []

[addresses]
sender = "49ba0b5bd7320c59a8fca6f885edc1dd2fee6e8f00258706376abdb90c3fa9c5"
admin_addr = "02f3d95f547aff823a4d00b44ed926558557e1d3374fce4ba2dd233e09e56c59"
[dev-addresses]

[dependencies]
AptosFramework = { local = "./framework/aptos-framework" }
AptosToken = { local = "./framework/aptos-token" }